### ISSUE TITLE
Issue with non-unix line endings

### ISSUE THREAD

**Issue by cmalard** [conventional-changelog-archived-repos/validate-commit-msg#18]
I spent some time trying to understand why I couldn't validate my commit message.
My editor had switched line endings to Windows `\r` so the regexp was not matched... and it was hard to find why :-)

We should tell what is going on or support other types of line endings.

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific pull request, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
Thanks for the issue @cmalard! I would actually recommend that you configure your editor to use unix style line endings. It's better for everyone if we use the same style.

However, if you'd like to submit a PR to support both I'd be happy to accept it.

**Comment by cmalard** [comment]
In fact I'm on Linux and my editor is configured to use Unix style so I don't figure what happened. Anyway :-)

**Comment by kentcdodds** [comment]
Would you like to create a PR to fix this or are you ok closing it?

**Comment by cmalard** [comment]
I do not commit myself on making a PR, maybe one day ^^
The issue will stay until then, so it's up to you to close it if you want `0 issue` but I do not vote for that ;-)

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
