### ISSUE TITLE
Fallback to finding config in same folder as node modules

### ISSUE THREAD

**Issue by Pajn** [conventional-changelog-archived-repos/validate-commit-msg#25]
We have multiple projects in a single repository, I placed a package.json in the root which runs installs this package, but as it checks for a config in the cwd rather than the package.json it's installed from I can't set any config.

Something like this

``` javascript
function getConfig() {
  var pkgFile = findup.sync(process.cwd(), 'package.json');
  var pkg = JSON.parse(fs.readFileSync(resolve(pkgFile, 'package.json')));

  if (pkg && pkg.config && pkg.config['validate-commit-msg']) {
    return pkg.config['validate-commit-msg'];
  }

  var fallbackPath = resolve(__dirname, '..', '..', 'package.json');
  try {
    fs.accessSync(fallbackPath, fs.R_OK);
    pkg = JSON.parse(fs.readFileSync(fallbackPath));
    return pkg && pkg.config && pkg.config['validate-commit-msg'] || {};
  } catch {
    return {};
  }
}
```

**Comment by kentcdodds** [comment]
Makes sense. I'd actually like to allow for configuring this with an `rc` file like `.validate-commit-msgrc` or something like that... Either way, I'd be interested to see a PR for this :+1:

**Comment by spirosikmd** [comment]
@kentcdodds I like your idea using an `rc` file. I was thinking we could support `.vcmrc`, and `package.json`. In the order that if `rc` is not present, then `package.json` is used. What do you think?

**Comment by kentcdodds** [comment]
Sounds great to me!

**Comment by spirosikmd** [comment]
Ok great! I will take a look and submit a PR.

**Comment by stevemao** [comment]
What about using https://www.npmjs.com/package/cosmiconfig?

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
