### ISSUE TITLE
Feature request: validate rebases through post-rewrite

### ISSUE THREAD

**Issue by joaocunha** [conventional-changelog-archived-repos/validate-commit-msg#38]
I'm not entirely sure if it's possible... but a great enhancement would be to also validate on `git rebase -i`.

We squash our commits prior to opening a PR, so running `git rebase -i master` will bypass the `commit-msg` validation.

From the [docs](https://git-scm.com/docs/githooks):

```
post-rewrite
This hook is invoked by commands that rewrite commits (git commit --amend, git-rebase; currently git-filter-branch does not call it!). Its first argument denotes the command it was invoked by: currently one of amend or rebase. Further command-dependent arguments may be passed in the future.

The hook receives a list of the rewritten commits on stdin, in the format

<old-sha1> SP <new-sha1> [ SP <extra-info> ] LF
The extra-info is again command-dependent. If it is empty, the preceding SP is also omitted. Currently, no commands pass any extra-info.

The hook always runs after the automatic note copying (see "notes.rewrite.<command>" in git-config[1]) has happened, and thus has access to these notes.

The following command-specific comments apply:

rebase
For the squash and fixup operation, all commits that were squashed are listed as being rewritten to the squashed commit. This means that there will be several lines sharing the same new-sha1.

The commits are guaranteed to be listed in the order that they were processed by rebase.
```

**Comment by kentcdodds** [comment]
I'm fairly certain that you could actually use this with the `post-rewrite` hook. [This](https://github.com/kentcdodds/validate-commit-msg/blob/d8a2d19a387e070ab115683443c8b3397ee1aba0/index.js#L132) is where it gets the commit message file. What changes do you think would be needed to support `post-rewrite`?

**Comment by joaocunha** [comment]
Ok, so two things:

1. The `git commit --amend` feature works even without the `post-rewrite` hook. Works as expected.
2. But if I add the rewrite hook, rebasing is no good, tho:

```
# some changes...

❯ git add . & git commit -m 'WIP 1'
Commit message validation ignored.
[reb-test 0393464] WIP 1
 1 file changed, 2 insertions(+), 1 deletion(-)

# more changes...

❯ git add . & git commit -m 'WIP 2'
Commit message validation ignored.
[reb-test 0393464] WIP 1
 1 file changed, 2 insertions(+), 1 deletion(-)

❯ git rebase -i master

# editor opens up
# squash WIP 2:
# pick 544b0d3 WIP 1
# s 7a9db3e WIP 2
# save and close

# the editor opens again for the commit message:
# write "invalid commit message"
# save and close

INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
invalid commit message

[detached HEAD 7df25ab] invalid commit message
 Date: Tue Jul 26 20:55:32 2016 -0300
 1 file changed, 3 insertions(+), 2 deletions(-)

INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
invalid commit message

Successfully rebased and updated refs/heads/reb-test.
```

As you can see, the validation ran twice, but the rebase was actually successful.

Also, it doesn't validate rebases without a `post-rewrite` hook (expected behavior).

**Comment by joaocunha** [comment]
Adding to that, if I write a valid commit message, it runs once and works fine.

With `WIP`:
```
❯ git rebase -i master
Commit message validation ignored.
[detached HEAD 3f690b0] WIP 3
 Date: Tue Jul 26 21:10:22 2016 -0300
 1 file changed, 3 insertions(+), 5 deletions(-)
Commit message validation ignored.
Successfully rebased and updated refs/heads/another-test.
```

With `feat()`:
```
❯ git rebase -i master
[detached HEAD dd1fb04] feat(valid): this is valid
 Date: Tue Jul 26 21:10:22 2016 -0300
 1 file changed, 3 insertions(+), 5 deletions(-)
Successfully rebased and updated refs/heads/another-test.
```

Hope this helps, @kentcdodds!

**Comment by kentcdodds** [comment]
Not certain I understand exactly 100%, but if you know what needs to happen, feel free to [makeapullrequest.com](http://makeapullrequest.com) :)

**Comment by mloayzagahona** [comment]
@kentcdodds 

I have a similar issue. I was trying to rebase like this:
```
$ git rebase -i HEAD~2
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
hook demo
[detached HEAD b4785fe] hook demo
 Date: Fri Jul 29 10:34:17 2016 -0400
 6 files changed, 97 insertions(+), 15 deletions(-)
 create mode 100644 myfolder/easecoverage.js
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
hook demo
Successfully rebased and updated refs/heads/hook.
```

The commit was created without the commit message format. It shown the error, but it is not canceling or rejecting the commit action for rebase (squashing commits)

Thanks

**Comment by joaocunha** [comment]
@kentcdodds I have edited my comment so you can better understand what's up: https://github.com/kentcdodds/validate-commit-msg/issues/38#issuecomment-235443884

**Comment by kentcdodds** [comment]
Yeah, I'm not sure how to solve this issue, but if you come up with something a pull request would be welcome :)

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
