### ISSUE TITLE
confusing option scope.validate

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog-archived-repos/validate-commit-msg#83]
if you set

```js
"config": {
    "validate-commit-msg": {
      "scope": {
        "required": true
      }
    }
  },
```

It doesn't actually validate scope. Unless you specify `scope.validate` to be `true` as well. So what's the point of `scope.validate`? It doesn't do anything except enabling other `scope` options.

**Comment by Garbee** [comment]
`scope.validate` enables the validation. `scope.required` means a scope is required to be provided in commit messages.

**Comment by stevemao** [comment]
Yeah but when I specify other scope options I already mean to validate it. If not I just turn off all scope options.

**Comment by Garbee** [comment]
ah yea, I see what you mean. hmm... Let me look into fixing that and remove the `validate` boolean.

**Comment by Garbee** [comment]
So, after doing the tweak to remove the option and looking through the tests to fix up. I feel like it is a backwards incompatible change to handle this in 2.x.

I would like to address this though, perhaps along with an ES6 rewrite that has been discussed as well to clean stuff up a bit.

**Comment by kentcdodds** [comment]
Might not be a bad idea to do an entire re-write. It's not a huge module after all. Also there's talk in #84 about making some big changes as well I think.

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
