### ISSUE TITLE
Allow multiple configuration options

### ISSUE THREAD

**Issue by Garbee** [conventional-changelog-archived-repos/validate-commit-msg#90]
Currently the config is hard-coded to use one type of file and only in JSON format. This is not as good for developers since they can't say, use `package.json`, or YAML to get comments, etc. V2 should take advantage of the [config](https://www.npmjs.com/package/config) package to allow multiple file types for the configuration as well as the ability to use `package.json`.

**Comment by spirosikmd** [comment]
Hey @Garbee! Configuration [through `package.json`](https://github.com/conventional-changelog/validate-commit-msg#usage) is supported, right? Though if `.vcmrc` is used it has precedence over `package.json` configuration.

**Comment by stevemao** [comment]
[cosmiconfig](https://www.npmjs.com/package/cosmiconfig) supports all major config options.

**Comment by spirosikmd** [comment]
This is a very good option @stevemao! It will fix #89 as well!

**Comment by Garbee** [comment]
Cosmic looks much better for a library target. I'll look at using that one before the other config library (which is more targeted towards full applications.)

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
